# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Opengrep

on:
  push:
    branches: [ "3.0.x" ]
  pull_request:
    branches: [ "3.0.x" ]

permissions:
  contents: read
  security-events: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Download / Install Opengrep"
        env:
          RELEASE_VERSION: v1.0.0-alpha.11

        run: |
          set -e

          echo "[+] Downloading Opengrep"
          curl -sSfL \
            -o "/usr/local/bin/opengrep" \
            "https://github.com/opengrep/opengrep/releases/download/${RELEASE_VERSION}/opengrep_manylinux_x86"
          chmod +x /usr/local/bin/opengrep

      - name: "Run Opengrep"
        run: opengrep scan --metrics=off --sarif-output ./results.sarif .

      - name: "Upload SARIF file"
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
        if: always()
